# Generated by Django 5.1.2 on 2024-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بیماری')),
                ('description', models.TextField(verbose_name='شرح بیماری')),
                ('is_priority', models.BooleanField(default=False, verbose_name='اولویت بودن / نبودن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'بیماری',
                'verbose_name_plural': 'بیماری ها',
            },
        ),
    ]
