# Generated by Django 5.1.2 on 2024-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_disease_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, verbose_name='عنوان بیماری')),
        ),
        migrations.AlterField(
            model_name='disease',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
