# Generated by Django 5.1.2 on 2024-11-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_disease_slug_alter_disease_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='slug',
        ),
    ]
