# Generated by Django 5.1.2 on 2024-11-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_disease_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='slug',
        ),
    ]
