# Generated by Django 5.1.2 on 2024-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_remove_disease_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
