# Generated by Django 5.1.2 on 2024-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_disease_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='slug',
            field=models.SlugField(),
        ),
    ]
