# Generated by Django 5.1.2 on 2024-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0008_alter_disease_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='summary_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='خلاصه شرح'),
        ),
    ]
