# Generated by Django 5.1.2 on 2024-11-13 12:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0009_disease_summary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='summary_description',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='خلاصه شرح'),
        ),
    ]
