# Generated by Django 5.1.2 on 2024-11-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0010_alter_disease_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='slug',
        ),
    ]
