# Generated by Django 5.1.2 on 2024-11-07 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diseases', '0002_alter_disease_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='ایمیل')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='تخصص')),
                ('gender', models.CharField(blank=True, choices=[('True', 'مرد'), ('False', 'زن')], default='True', max_length=50, null=True, verbose_name='جنسیت')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('active_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد احراز')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل')),
                ('patient_national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='سوابق بیماری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_dentist', to=settings.AUTH_USER_MODEL, verbose_name='دندانپزشک مریض')),
                ('diseases', models.ManyToManyField(related_name='patients', to='diseases.disease', verbose_name='بیماری ها')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیمار ها',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ مراجعه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.patient')),
            ],
        ),
    ]
