# Generated by Django 5.1.2 on 2024-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ مراجعه'),
        ),
    ]
