# Generated by Django 5.1.2 on 2024-11-09 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_visit_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 14, 32, 38, 931850), verbose_name='تاریخ مراجعه'),
        ),
    ]
