# Generated by Django 5.1.2 on 2024-11-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_visit_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
