# Generated by Django 5.1.2 on 2024-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_visit_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='شماره موبایل')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ مراجعه'),
        ),
    ]
