# Generated by Django 5.1.2 on 2024-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactus_alter_visit_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع'),
        ),
    ]
