# Generated by Django 5.1.2 on 2024-11-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_visit_remove_patient_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.visit', verbose_name='تاریخ مراجعه'),
        ),
    ]
