# Generated by Django 5.1.2 on 2024-11-06 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_family_alter_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_dentist', to=settings.AUTH_USER_MODEL, verbose_name='دندانپزشک مریض'),
        ),
    ]
